version: "3.0"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PROJECT_HOST=127.0.0.1
      - PROJECT_PORT=8080
    volumes:
      - .:/app
    depends_on:
      postgres-fastapi:
        condition: service_healthy

  postgres-fastapi:
    image: postgres:16
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collection
    container_name: postgres-fastapi
    restart: unless-stopped

